{
   "name": "ci",
   "on": {
      "push": {
         "branches": [
            "main",
            "test"
         ]
      }
   },
   "jobs": {
      "build": {
         "name": "build",
         "permissions": {
            "contents": "read",
            "id-token": "write"
         },
         "runs-on": "ubuntu-latest",
         "steps": [
            {
               "uses": "docker/setup-buildx-action@v2"
            },
            {
               "uses": "aws-actions/configure-aws-credentials@v4",
               "with": {
                  "aws-region": "us-west-2",
                  "role-to-assume": "arn:aws:iam::341857463381:role/gha-docker-generic",
                  "role-skip-session-tagging": true,
                  "mask-aws-account-id": false
               }
            },
            {
               "id": "login-ecr",
               "uses": "aws-actions/amazon-ecr-login@v2"
            },
            {
               "uses": "docker/build-push-action@v3",
               "with": {
                  "context": "{{defaultContext}}",
                  "platforms": "linux/amd64",
                  "push": true,
                  "tags": "${{ steps.login-ecr.outputs.registry }}/netbox:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/netbox:latest"
               }
            }
         ]
      }
   }
}
